server:
  port: 8003
 
spring:
  application:
    name: proxy-server
  datasource:
    url: jdbc:mysql://localhost:3306/testing
    username: root
    password:
  jpa: 
    hibernate:
      ddl-auto: update
          
  cloud:
    config:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true 
      routes:
      - id: users
        uri: lb://admin-application
        predicates:
          - Path=/admin/**
          
    discovery:
      enabled: true
      serviceId: config-server
    fail-fast: true
    retry:
      initialInterval: 2000
      maxAttempts: 30

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1
