package com.resource.common.constants;

import java.util.Arrays;
import java.util.List;

public enum City {

	NOT_AVAILABLE(0, "Not available"),
	OTHERS(40, "OTHERS"),
	
	// INDIAN CITIES
	MUMBAI(1, "Mumbai"),
	DELHI(2, "Delhi"),
	BANGALORE(3, "Bangalore"),
	HYDERABAD(4, "Hyderabad"),
	AHMEDABAD(5, "Ahmedabad"),
	CHENNAI(6, "Chennai"),
	KOLKATA(7, "Kolkata"),
	SURAT(8, "Surat"),
	PUNE(9, "Pune"),
	JAIPUR(10, "Jaipur"),
	LUCKNOW(11, "Lucknow"),
	KANPUR(12, "Kanpur"),
	NAGPUR(13, "Nagpur"),
	INDORE(14, "Indore"),
	THANE(15, "Thane"),
	BHOPAL(16, "Bhopal"),
	VISAKHAPATNAM(17, "Visakhapatnam"),
	PIMPRICHINCHWAD(18, "Pimpri Chinchwad"),
	PATNA(19, "Patna"),
	VADODARA(20, "Vadodara"),
	GHAZIABAD(21, "Ghaziabad"),
	LUDHIANA(22, "Ludhiana"),
	AGRA(23, "Agra"),
	NASHIK(24, "Nashik"),
	FARIDABAD(25, "Faridabad"),
	MEERUT(26, "Meerut"),
	RAJKOT(27, "Rajkot"),
	KALYANDOMBIVLI(28, "Kalyan Dombivli"),
	VASAIVIRAR(29, "Vasai Virar"),
	VARANASI(30, "Varanasi"),
	SRINAGAR(31, "Srinagar"),
	DHANBAD(32, "Dhanbad"),
	AMRITSAR(33, "Amritsar"),
	NAVIMUMBAI(34, "NaviMumbai"),
	ALLAHABAD(35, "Allahabad"),
	HOWRAH(36, "Howrah"),
	RANCHI(37, "Ranchi"),
	GWALIOR(38, "Gwalior"),
	JABALPUR(39, "Jabalpur"),
	COIMBATORE(40, "Coimbatore"),
	VIJAYAWADA(41, "Vijayawada"),
	JODHPUR(42, "Jodhpur"),
	MADURAI(43, "Madurai"),
	RAIPUR(44, "Raipur"),
	KOTA(45, "Kota"),
	CHANDIGARH(46, "Chandigarh"),
	GUWAHATI(47, "Guwahati"),
	SOLAPUR(48, "Solapur"),
	HUBLIDHARWAD(49, "Hubli–Dharwad"),
	TIRUCHIRAPPALLI(50, "Tiruchirappalli"),
	BAREILLY(51, "Bareilly"),
	MYSORE(52, "Mysore"),
	TIRUPPUR(53, "Tiruppur"),
	GURGAON(54, "Gurgaon"),
	ALIGARH(55, "Aligarh"),
	JALANDHAR(56, "Jalandhar"),
	BHUBANESWAR(57, "Bhubaneswar"),
	SALEM(58, "Salem"),
	MIRABHAYANDAR(59, "Mira Bhayandar"),
	WARANGAL(60, "Warangal"),
	JALGAON(61, "Jalgaon"),
	GUNTUR(62, "Guntur"),
	BHIWANDI(63, "Bhiwandi"),
	SAHARANPUR(64, "Saharanpur"),
	GORAKHPUR(65, "Gorakhpur"),
	BIKANER(66, "Bikaner"),
	AMRAVATI(67, "Amravati"),
	NOIDA(68, "Noida"),
	JAMSHEDPUR(69, "Jamshedpur"),
	BHILAI(70, "Bhilai"),
	CUTTACK(71, "Cuttack"),
	FIROZABAD(72, "Firozabad"),
	KOCHI(73, "Kochi"),
	NELLORE(74, "Nellore"),
	BHAVNAGAR(75, "Bhavnagar"),
	DEHRADUN(76, "Dehradun"),
	DURGAPUR(77, "Durgapur"),
	ASANSOL(78, "Asansol"),
	ROURKELA(79, "Rourkela"),
	NANDED(80, "Nanded"),
	KOLHAPUR(81, "Kolhapur"),
	AJMER(82, "Ajmer"),
	AKOLA(83, "Akola"),
	GULBARGA(84, "Gulbarga"),
	JAMNAGAR(85, "Jamnagar"),
	UJJAIN(86, "Ujjain"),
	LONI(87, "Loni"),
	SILIGURI(88, "Siliguri"),
	JHANSI(89, "Jhansi"),
	ULHASNAGAR(90, "Ulhasnagar"),
	JAMMU(91, "Jammu"),
	SANGLIMIRAJKUPWAD(92, "Sangli Miraj & Kupwad"),
	MANGALORE(93, "Mangalore"),
	ERODE(94, "Erode"),
	BELGAUM(95, "Belgaum"),
	AMBATTUR(96, "Ambattur"),
	TIRUNELVELI(97, "Tirunelveli"),
	MALEGAON(98, "Malegaon"),
	GAYA(99, "Gaya"),
	THIRUVANANTHAPURAM(100, "Thiruvananthapuram"),
	UDAIPUR(101, "Udaipur"),
	MAHESHTALA(102, "Maheshtala"),
	DAVANAGERE(103, "Davanagere"),
	KOZHIKODE(104, "Kozhikode"),
	KURNOOL(105, "Kurnool"),
	RAJPURSONARPUR(106, "RajpurSonarpur"),
	RAJAHMUNDRY(107, "Rajahmundry"),
	BOKARO(108, "Bokaro"),
	SOUTHDUMDUM(109, "SouthDumdum"),
	BELLARY(110, "Bellary"),
	PATIALA(111, "Patiala"),
	GOPALPUR(112, "Gopalpur"),
	AGARTALA(113, "Agartala"),
	BHAGALPUR(114, "Bhagalpur"),
	MUZAFFARNAGAR(115, "Muzaffarnagar"),
	BHATPARA(116, "Bhatpara"),
	PANIHATI(117, "Panihati"),
	LATUR(118, "Latur"),
	DHULE(119, "Dhule"),
	TIRUPATI(120, "Tirupati"),
	ROHTAK(121, "Rohtak"),
	KORBA(122, "Korba"),
	BHILWARA(123, "Bhilwara"),
	BERHAMPUR(124, "Berhampur"),
	MUZAFFARPUR(125, "Muzaffarpur"),
	AHMEDNAGAR(126, "Ahmednagar"),
	MATHURA(127, "Mathura"),
	KOLLAM(128, "Kollam"),
	AVADI(129, "Avadi"),
	KADAPA(130, "Kadapa"),
	KAMARHATI(131, "Kamarhati"),
	SAMBALPUR(132, "Sambalpur"),
	BILASPUR(133, "Bilaspur"),
	SHAHJAHANPUR(134, "Shahjahanpur"),
	SATARA(135, "Satara"),
	BIJAPUR(136, "Bijapur"),
	KAKINADA(137, "Kakinada"),
	RAMPUR(138, "Rampur"),
	SHIMOGA(139, "Shimoga"),
	CHANDRAPUR(140, "Chandrapur"),
	JUNAGADH(141, "Junagadh"),
	THRISSUR(142, "Thrissur"),
	ALWAR(143, "Alwar"),
	BARDHAMAN(144, "Bardhaman"),
	KULTI(145, "Kulti"),
	NIZAMABAD(146, "Nizamabad"),
	PARBHANI(147, "Parbhani"),
	TUMKUR(148, "Tumkur"),
	KHAMMAM(149, "Khammam"),
	OZHUKARAI(150, "Ozhukarai"),
	BIHARSHARIF(151, "BiharSharif"),
	PANIPAT(152, "Panipat"),
	DARBHANGA(153, "Darbhanga"),
	BALLY(154, "Bally"),
	AIZAWL(155, "Aizawl"),
	DEWAS(156, "Dewas"),
	ICHALKARANJI(157, "Ichalkaranji"),
	KARNAL(158, "Karnal"),
	BATHINDA(159, "Bathinda"),
	JALNA(160, "Jalna"),
	ELURU(161, "Eluru"),
	BARASAT(162, "Barasat"),
	KIRARISULEMANNAGAR(163, "KirariSulemanNagar"),
	PURNIA(164, "Purnia"),
	SATNA(165, "Satna"),
	MAU(166, "Mau"),
	SONIPAT(167, "Sonipat"),
	FARRUKHABAD(168, "Farrukhabad"),
	SAGAR(169, "Sagar"),
	DURG(170, "Durg"),
	IMPHAL(171, "Imphal"),
	RATLAM(172, "Ratlam"),
	HAPUR(173, "Hapur"),
	ARRAH(174, "Arrah"),
	ANANTAPUR(175, "Anantapur"),
	KARIMNAGAR(176, "Karimnagar"),
	ETAWAH(177, "Etawah"),
	AMBARNATH(178, "Ambarnath"),
	NORTHDUMDUM(179, "NorthDumdum"),
	BHARATPUR(180, "Bharatpur"),
	BEGUSARAI(181, "Begusarai"),
	NEWDELHI(182, "NewDelhi"),
	GANDHIDHAM(183, "Gandhidham"),
	BARANAGAR(184, "Baranagar"),
	TIRUVOTTIYUR(185, "Tiruvottiyur"),
	PONDICHERRY(186, "Pondicherry"),
	SIKAR(187, "Sikar"),
	THOOTHUKUDI(188, "Thoothukudi"),
	REWA(189, "Rewa"),
	MIRZAPUR(190, "Mirzapur"),
	RAICHUR(191, "Raichur"),
	PALI(192, "Pali"),
	RAMAGUNDAM(193, "Ramagundam"),
	HARIDWAR(194, "Haridwar"),
	VIJAYANAGARAM(195, "Vijayanagaram"),
	KATIHAR(196, "Katihar"),
	NAGERCOIL(197, "Nagercoil"),
	SRIGANGANAGAR(198, "SriGanganagar"),
	KARAWALNAGAR(199, "KarawalNagar"),
	MANGO(200, "Mango"),
	THANJAVUR(201, "Thanjavur"),
	BULANDSHAHR(202, "Bulandshahr"),
	ULUBERIA(203, "Uluberia"),
	KATNI(204, "Katni"),
	SAMBHAL(205, "Sambhal"),
	SINGRAULI(206, "Singrauli"),
	NADIAD(207, "Nadiad"),
	SECUNDERABAD(208, "Secunderabad"),
	NAIHATI(209, "Naihati"),
	YAMUNANAGAR(210, "Yamunanagar"),
	BIDHANNAGAR(211, "Bidhannagar"),
	PALLAVARAM(212, "Pallavaram"),
	BIDAR(213, "Bidar"),
	MUNGER(214, "Munger"),
	PANCHKULA(215, "Panchkula"),
	BURHANPUR(216, "Burhanpur"),
	RAURKELAINDUSTRIALTOWNSHIP(217, "RaurkelaIndustrialTownship"),
	KHARAGPUR(218, "Kharagpur"),
	DINDIGUL(219, "Dindigul"),
	GANDHINAGAR(220, "Gandhinagar"),
	HOSPET(221, "Hospet"),
	NANGLOIJAT(222, "NangloiJat"),
	MALDA(223, "Malda"),
	ONGOLE(224, "Ongole"),
	DEOGHAR(225, "Deoghar"),
	CHAPRA(226, "Chapra"),
	HALDIA(227, "Haldia"),
	KHANDWA(228, "Khandwa"),
	NANDYAL(229, "Nandyal"),
	MORENA(230, "Morena"),
	AMROHA(231, "Amroha"),
	ANAND(232, "Anand"),
	BHIND(233, "Bhind"),
	BHALSWAJAHANGIRPUR(234, "BhalswaJahangirPur"),
	MADHYAMGRAM(235, "Madhyamgram"),
	BHIWANI(236, "Bhiwani"),
	BERHAMPORE(237, "Berhampore"),
	AMBALA(238, "Ambala"),
	MORBI(239, "Morbi"),
	FATEHPUR(240, "Fatehpur"),
	RAEBARELI(241, "Raebareli"),
	MAHABOOBNAGAR(242, "Mahaboobnagar"),
	CHITTOOR(243, "Chittoor"),
	BHUSAWAL(244, "Bhusawal"),
	ORAI(245, "Orai"),
	BAHRAICH(246, "Bahraich"),
	VELLORE(247, "Vellore"),
	MEHSANA(248, "Mehsana"),
	RAIGANJ(249, "Raiganj"),
	SIRSA(250, "Sirsa"),
	DANAPUR(251, "Danapur"),
	SERAMPORE(252, "Serampore"),
	SULTANPURMAJRA(253, "SultanPurMajra"),
	GUNA(254, "Guna"),
	JAUNPUR(255, "Jaunpur"),
	PANVEL(256, "Panvel"),
	SHIVPURI(257, "Shivpuri"),
	SURENDRANAGARDUDHREJ(258, "SurendranagarDudhrej"),
	UNNAO(259, "Unnao"),
	CHINSURAH(260, "Chinsurah"),
	ALAPPUZHA(261, "Alappuzha"),
	KOTTAYAM(262, "Kottayam"),
	MACHILIPATNAM(263, "Machilipatnam"),
	SHIMLA(264, "Shimla"),
	ADONI(265, "Adoni"),
	UDUPI(266, "Udupi"),
	TENALI(267, "Tenali"),
	PRODDATUR(268, "Proddatur"),
	SAHARSA(269, "Saharsa"),
	HINDUPUR(270, "Hindupur"),
	SASARAM(271, "Sasaram"),
	HAJIPUR(272, "Hajipur"),
	BHIMAVARAM(273, "Bhimavaram"),
	KUMBAKONAM(274, "Kumbakonam"),
	DEHRI(275, "Dehri"),
	MADANAPALLE(276, "Madanapalle"),
	SIWAN(277, "Siwan"),
	BETTIAH(278, "Bettiah"),
	GUNTAKAL(279, "Guntakal"),
	SRIKAKULAM(280, "Srikakulam"),
	MOTIHARI(281, "Motihari"),
	DHARMAVARAM(282, "Dharmavaram"),
	GUDIVADA(283, "Gudivada"),
	PHAGWARA(284, "Phagwara"),
	NARASARAOPET(285, "Narasaraopet"),
	SURYAPET(286, "Suryapet"),
	MIRYALAGUDA(287, "Miryalaguda"),
	TADIPATRI(288, "Tadipatri"),
	KARAIKUDI(289, "Karaikudi"),
	KISHANGANJ(290, "Kishanganj"),
	JAMALPUR(291, "Jamalpur"),
	KAVALI(292, "Kavali"),
	TADEPALLIGUDEM(293, "Tadepalligudem"),
	AMARAVATI(294, "Amaravati"),
	BUXAR(295, "Buxar"),
	JEHANABAD(296, "Jehanabad"),
	AURANGABAD(297, "Aurangabad"),
	GANGTOK(298, "Gangtok");
	
	private Integer id;
	private String name;

	City(Integer id, String name) {
		this.id = id;
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	public Integer getId() {
		return this.id;
	}

	public static City getCity(Integer id) {
		for (City city : City.values()) {
			if (city.getId() == id) {
				return city;
			}
		}
		return null;
	}
	
	public static List<City> geCities() {
   	 	return Arrays.asList(City.values());
    }
}
